# Usar la imagen base de nginx
FROM nginx:latest

# Copiar el index.html a la ubicación predeterminada de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80
EXPOSE 80
